# Generated by Django 4.1.3 on 2022-11-02 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=160)),
                ('transaction_count', models.PositiveBigIntegerField(default=0)),
                ('final_balance', models.PositiveBigIntegerField(default=0)),
                ('last_successfull_sync', models.DateTimeField(null=True)),
                ('sync_status', models.CharField(choices=[('NEVER', 'Never'), ('SCHEDULED', 'Scheduled'), ('STARTED', 'Started'), ('FAILED', 'Failed'), ('COMPLETED', 'Completed')], default='NEVER', max_length=12)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'address')},
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=255)),
                ('inputs', models.JSONField(default=dict)),
                ('out', models.JSONField(default=dict)),
                ('fee', models.PositiveBigIntegerField()),
                ('date', models.DateTimeField()),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.address')),
            ],
            options={
                'unique_together': {('address', 'hash')},
            },
        ),
    ]
