# Generated by Django 4.1.3 on 2022-11-16 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_address_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='last_successfull_sync',
        ),
        migrations.RemoveField(
            model_name='address',
            name='sync_status',
        ),
    ]
